---
- name: Install bind9
  apt:
    name: bind9
    state: latest

- name: conf named.conf.local
  copy:
    src: etc/bind9/named.conf.local
    dest: /etc/bind/named.conf.local
    owner: bind
    group: bind
    mode: 0644

- name: conf zones
  copy:
    src: etc/bind9/zones.rfc1918
    dest: /etc/bind/zones.rfc1918
    owner: bind
    group: bind
    mode: 0644

- name: añadir zonas db.example
  copy:
    src: var/cache/bind9/db.example
    dest: /var/cache/bind/db.example
    owner: bind
    group: bind
    mode: 0644

- name: añadir zona db.172.0.16
  copy:
    src: var/cache/bind9/db.172.16.0
    dest: /var/cache/bind/db.172.16.0
    owner: bind
    group: bind
    mode: 0644
  notify:
    - restart bind9
