---
- name: Install bind9
  apt:
    name: bind9
    state: latest

- name: conf named.conf.local
  copy:
    src: files/bind/named.conf.local
    dest: /etc/bind/named.conf.local
    owner: bind
    group: bind
    mode: 0644

- name: conf zones
  copy:
    src: files/bind/zones.rfc1918
    dest: /etc/bind/zones.rfc1918
    owner: bind
    group: bind
    mode: 0644

- name: añadir zonas db.example
  copy:
    src: files/conf/db.example
    dest: /var/cache/bind/db.example
    owner: bind
    group: bind
    mode: 0644

- name: añadir zona db.10.0.0
  copy:
    src: files/conf/db.10.0.0
    dest: /var/cache/bind/db.10.0.0
    owner: bind
    group: bind
    mode: 0644
  notify:
    - restart bind9
