---
- name: Descargar Drupal
  unarchive:
    src: https://www.drupal.org/download-latest/tar.gz
    dest: /var/www/
    remote_src: yes

- name: renombrar directory
  shell: mv /var/www/drupal* /var/www/drupal

- name: crear sites/default/files
  file:
    path: /var/www/drupal/sites/default/files
    state: directory
    owner: root
    group: root
    mode: 0666

- name: configuracion settings.php 
  copy:
    src: /var/www/drupal/sites/default/default.settings.php
    dest: /var/www/drupal/sites/default/settings.php 
    remote_src: yes
    owner: root
    group: root
    mode: 0666

- name: Descargar Drush  
  get_url:
    url: https://github.com/drush-ops/drush/releases/download/8.1.18/drush.phar
    dest: /usr/local/bin/drush
    owner: root
    group: root
    mode: 0755

- name: cambiar directorio /var/www/drupal
  shell: cd /var/www/drupal

- name: Install Drupal Drush
  shell: cd /var/www/drupal && drush site-install standard -y --site-name="Despliegue de Drupal con Ansible" --account-name="admin" --account-pass="admin" --db-url=pgsql://admin:admin@10.0.0.10/drupal -y

- name: Deshabilitar CSS y JS 
  shell: cd /var/www/drupal && drush -y config-set system.performance css.preprocess 0 && drush -y config-set system.performance js.preprocess 0
  notify:
  - restart apache2
