---
- name: Install apache2
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - apache2
    - libapache2-mod-php7.0
    - php7.0
    - php7.0-pgsql
    - php7.0-xml
    - php7.0-mbstring
    - php7.0-gd
    - postgresql-client

- name: Configuracion virtualhost
  copy:
    src: configuraciones/apache2/apachedrupal.conf
    dest: /etc/apache2/sites-available/drupal.conf 
    owner: root
    group: root
    mode: 0644

- name: habilitar virtualhost
  file:
    src: configuraciones/apache2/apachedrupal.conf
    dest: /etc/apache2/sites-enabled/drupal.conf
    owner: root
    group: root
    state: link

- name: deshabilitar default virtualhost
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify:
- restart apache2
