---
- name: Instalar bind9
  apt:
    name: bind9
    state: latest

- name: conf named.conf.local
  copy:
    src: configuraciones/bind9/templates/named.conf.local
    dest: /etc/bind/named.conf.local
    owner: bind
    group: bind
    mode: 0644

- name: conf zone
  copy:
    src: configuraciones/bind9/templates/zones.rfc1918
    dest: /etc/bind/zones.rfc1918
    owner: bind
    group: bind
    mode: 0644

- name: añadir zona db.example
  copy:
    src: configuraciones/bind9/zonas/db.example.com
    dest: /var/cache/bind/db.example.com
    owner: bind
    group: bind
    mode: 0644

- name: aañdir zona file db.0.0.10
  copy:
    src: configuraciones/bind9/zonas/db.0.0.10
    dest: /var/cache/bind/db.0.0.10
    owner: bind
    group: bind
    mode: 0644
  notify:
- restart bind9
